### ISSUE TITLE
libsigrok make error: unknown type name 'ssize_t'

### ISSUE THREAD

**Issue by robomechs** [oxyum/sigrok#1]
Linux debian w
libsigrok make error: unknown type name 'ssize_t'
look like missing "#include <sys/types.h>"

**Comment by oxyum** [comment]
Man, this repo is stale for 6 years. Try code from https://sigrok.org/gitweb/

**Comment by robomechs** [comment]
Yes, I've seen. But I can't find ways to contact sigrok. I used latest sources.

**Comment by oxyum** [comment]
They have [bugzilla](https://sigrok.org/bugzilla/) for reports and IRC: [#sigrok@freenode](http://webchat.freenode.net/?channels=%23sigrok&uio=MT1mYWxzZQ9a)
