### ISSUE TITLE
configure libsigrokcode error

### ISSUE THREAD

**Issue by robomechs** [oxyum/sigrok#2]
Linux debian wheezy
configure libsigrokdecode error: Package requirements (glib-2.0>= 2.34 python3 >=3.2) were not met.
I spend about 2hours to get this step. Now I give up. For today, building the program is too time-consuming. maybe next time.

**Comment by robomechs** [comment]
*libsigrokDEcode

**Comment by oxyum** [comment]
Man, this repo is stale for 6 years. Try code from https://sigrok.org/gitweb/
